generate_notes:
  description: "Organize the provided raw class notes into well-structured and readable summaries."
  expected_output: "A detailed and clean summary of the raw notes."
  agent: note_organizer

assist_study:
  description: "Help explain a difficult topic to a student, breaking it down into simple language."
  expected_output: "A detailed explanation in plain and simple words."
  agent: study_assistant

create_content:
  description: "Generate multiple-choice questions and flashcards based on a topic."
  expected_output: "A list of 5 MCQs and 5 flashcards."
  agent: content_generator

manage_tasks:
  description: "Oversee and manage the workflow by assigning tasks to agents and ensuring goals are met."
  expected_output: "A plan describing which agent will do what."
  agent: task_manager
